/**
 * Message types shared between the VS Code extension host and the webview.
 * This file defines the complete protocol for communication.
 */

/**
 * A diff hunk within a file. Used for precise commit grouping.
 */
export interface DiffHunk {
  /** Zero-based index of the hunk within the file's diff. */
  hunkIndex: number;
  /** Hunk header, e.g. "@@ -20,7 +20,12 @@" */
  header: string;
  /** The complete hunk body including the header. */
  content: string;
  /** The file this hunk belongs to. */
  file: string;
}

/**
 * A change group pointing to specific hunks in specific files.
 */
export interface Change {
  /** Path of the file containing the hunks. */
  file: string;
  /** Zero-based indices of the hunks assigned to this commit. */
  hunks: number[];
}

/**
 * A single proposed commit within the plan.
 */
export interface CommitGroup {
  /** Unique ID generated by the extension. */
  id: string;
  /** Conventional commit type: feat, fix, refactor, docs, style, test, chore, perf, ci, build, revert. */
  type: string;
  /** Short commit subject line. */
  subject: string;
  /** Bullet-point lines for the commit body. */
  body: string[];
  /** Files and hunks included in this commit. */
  changes: Change[];
  /** Reason-for-grouping explanation returned by the AI. */
  reasoning?: string;
}

/**
 * The complete AI-generated plan.
 */
export interface CommitPlan {
  commits: CommitGroup[];
}

/**
 * Detailed status of the staged changes.
 */
export interface StagedChangeSummary {
  /** Total number of staged files. */
  fileCount: number;
  /** Total lines added. */
  additions: number;
  /** Total lines deleted. */
  deletions: number;
  /** List of staged file paths. */
  files: string[];
}

/**
 * Messages sent from the webview to the extension host.
 */
export type WebviewToExtensionMessage =
  | { command: "refresh" }
  | { command: "generate" }
  | { command: "regenerate" }
  | { command: "clearPlan" }
  | { command: "commit"; plan: CommitPlan }
  | { command: "commitSelected"; plan: CommitPlan; commitIds: string[] }
  | { command: "viewDiff"; commit: CommitGroup }
  | { command: "editCommit"; commit: CommitGroup };

/**
 * Messages sent from the extension host to the webview.
 */
export type ExtensionToWebviewMessage =
  | { command: "refreshDone"; summary: StagedChangeSummary | null }
  | { command: "setLoading"; value: boolean }
  | { command: "planGenerated"; plan: CommitPlan }
  | { command: "planRegenerated"; plan: CommitPlan }
  | { command: "error"; message: string }
  | { command: "commitSuccess"; count: number }
  | { command: "commitProgress"; current: number; total: number; subject: string };