/**
 * Message types shared between the VS Code extension host and the webview.
 * This file defines the complete protocol for communication.
 *
 * There are two layers:
 *  1. Internal AI types (`CommitGroup`, `CommitPlan`) — hunk-based plan
 *     produced by the AI providers.
 *  2. UI types (`DraftCommit`, `DraftCommitPlan`) — the master-detail
 *     webview representation used by the editor tab.
 */
import { ProviderConfig } from "./provider";

/**
 * A diff hunk within a file. Used for precise commit grouping.
 */
export interface DiffHunk {
  /** Zero-based index of the hunk within the file's diff. */
  hunkIndex: number;
  /** Hunk header, e.g. "@@ -20,7 +20,12 @@" */
  header: string;
  /** The complete hunk body including the header. */
  content: string;
  /** The file this hunk belongs to. */
  file: string;
}

/**
 * A change group pointing to specific hunks in specific files.
 */
export interface Change {
  /** Path of the file containing the hunks. */
  file: string;
  /** Zero-based indices of the hunks assigned to this commit. */
  hunks: number[];
}

/**
 * A single proposed commit within the AI plan (internal, hunk-based).
 */
export interface CommitGroup {
  /** Unique ID generated by the extension. */
  id: string;
  /** Conventional commit type: feat, fix, refactor, docs, style, test, chore, perf, ci, build, revert. */
  type: string;
  /** Short commit subject line. */
  subject: string;
  /** Bullet-point lines for the commit body. */
  body: string[];
  /** Files and hunks included in this commit. */
  changes: Change[];
  /** Reason-for-grouping explanation returned by the AI. */
  reasoning?: string;
  /** A single prose paragraph explaining what changed & why (display only, NOT part of the commit). */
  overview?: string;
}

/**
 * Internal AI plan produced by providers (hunk-based).
 */
export interface CommitPlan {
  commits: CommitGroup[];
}

/**
 * Detailed status of the staged changes.
 */
export interface StagedChangeSummary {
  /** Total number of staged files. */
  fileCount: number;
  /** Total lines added. */
  additions: number;
  /** Total lines deleted. */
  deletions: number;
  /** List of staged file paths. */
  files: string[];
}

/**
 * A single file's diff, computed from staged changes.
 */
export interface FileDiff {
  /** Path of the file relative to workspace root. */
  path: string;
  /** Whether the file was added, modified, or deleted. */
  status: "ADDED" | "MODIFIED" | "DELETED";
  /** Number of additions. */
  additions: number;
  /** Number of deletions. */
  deletions: number;
  /** The raw unified diff text for this file. */
  diffText: string;
}

/**
 * A single draft commit shown in the left timeline of the editor tab.
 */
export interface DraftCommit {
  id: string;
  type: string;
  subject: string;
  overview: string;
  files: FileDiff[];
  /** A single prose paragraph explaining what changed & why (display only, NOT part of the commit). */
  aiOverview?: string;
}

/**
 * The complete UI plan (list of draft commits) shown in the editor tab.
 */
export interface DraftCommitPlan {
  commits: DraftCommit[];
  summary: string;
}

/**
 * Messages sent from the webview to the extension host.
 */
export type WebviewToExtensionMessage =
  | { command: "loadStaged" }
  | { command: "reloadChanges" }
  | { command: "generatePlan"; prompt?: string; model?: string; instructions?: string; sampleMessage?: string }
  | { command: "regenerateSingle"; commitId: string; prompt?: string }
  | { command: "executeCommits"; plan: DraftCommitPlan }
  | { command: "getProviderConfig" }
  | { command: "saveProviderConfig"; config: ProviderConfig }
  | { command: "testProviderConnection"; config: ProviderConfig }
  | { command: "promptApiKey"; provider: string; label: string; requiresApiKey: boolean }
  | { command: "openEditor" }
  | { command: "getRemoteInfo" }
  | { command: "generatePrContent"; title?: boolean; description?: boolean; plan?: DraftCommitPlan }
  | {
      command: "createPullRequest";
      remote: string;
      baseBranch: string;
      headBranch: string;
      title: string;
      body: string;
    };

/**
 * Git state snapshot sent to track when the working directory changes, so the
 * webview can compare it against the currently-loaded diffs.
 */
export interface GitStatusSnapshot {
  staged: number;
  unstaged: number;
  /** A stable signature of the staged files to detect real content changes. */
  filesSignature: string;
  /** File count of the currently loaded staged diff. */
  loadedCount: number;
}

/**
 * A single real-time activity/log entry shown in the webview status panel.
 */
export interface ActivityItem {
  id: string;
  message: string;
  type: "info" | "success" | "error" | "loading" | "warning";
  timestamp: string;
}

/**
 * Messages sent from the extension host to the webview.
 */
export type ExtensionToWebviewMessage =
  | { command: "setStagedOverview"; files: FileDiff[] }
  | { command: "setLoading"; value: boolean }
  | { command: "planGenerated"; plan: DraftCommitPlan }
  | { command: "singleRegenerated"; commit: DraftCommit }
  | { command: "changesDetected"; staged: number; unstaged: number }
  | { command: "gitSnapshot"; snapshot: GitStatusSnapshot }
  | { command: "apiKeyPrompted"; provider: string; label: string }
  | { command: "activity"; activity: ActivityItem }
  | { command: "error"; message: string }
  | { command: "providerConfigLoaded"; config: ProviderConfig }
  | { command: "providerTestResult"; success: boolean; message: string }
  | { command: "providerApiKeyStatus"; status: Record<string, boolean> }
  | {
      command: "remoteInfoLoaded";
      remotes: { name: string; url: string }[];
      branches: string[];
      currentBranch: string;
      defaultBranch: string;
    }
  | { command: "prContentGenerated"; title?: string; description?: string }
  | { command: "prCreated"; url?: string; message?: string };