/**
 * Provider abstractions for the AI features of the composer.
 *
 * `AIProvider` exposes three high-level operations; every concrete provider
 * only implements one low-level primitive (`complete`) through
 * `BaseAIProvider`, so prompt building, JSON parsing and normalization live in
 * exactly one place.
 */

import { CommitPlan } from "../types/messages";

/** Context about the repository passed to the AI provider. */
export interface RepositoryContext {
  /** Annotated staged diff (hunk-indexed). */
  diff: string;
  /** Current branch name, if available. */
  branch?: string;
  /** Repository name (from folder name). */
  repoName?: string;
  /** Optional user instructions to bias the commit plan. */
  instructions?: string;
  /** Optional sample commit message used as a style reference. */
  sampleMessage?: string;
}

/** Context for regenerating a single commit message. */
export interface CommitMessageContext {
  /** Annotated diff containing only this commit's hunks. */
  diff: string;
  /** File paths touched by the commit (context only, never quoted in the body). */
  files: string[];
  /** Current commit type. */
  type: string;
  /** Current commit subject. */
  subject: string;
  /** Current branch name, if available. */
  branch?: string;
  /** Repository name (from folder name). */
  repoName?: string;
  /** Optional user instructions to bias the message. */
  instructions?: string;
  /** Optional sample commit message used as a style reference. */
  sampleMessage?: string;
}

/** Raw commit message returned by the AI for a single commit. */
export interface CommitMessageDraft {
  type: string;
  scope?: string;
  breaking?: boolean;
  subject: string;
  body: string[];
  overview?: string;
}

/** Pull request content generated by an AI provider. */
export interface PrContent {
  title: string;
  description: string;
}

/** A commit included in a pull request. */
export interface PrCommit {
  subject: string;
  body?: string;
}

/** Low-level completion request understood by every provider. */
export interface CompletionRequest {
  /** Optional system instruction. */
  system?: string;
  /** User prompt. */
  user: string;
  /** Ask the provider to return JSON only (when supported). */
  json?: boolean;
  /** Maximum response tokens (when supported). */
  maxTokens?: number;
}

/**
 * AIProvider is the abstraction for the AI features the composer needs.
 */
export interface AIProvider {
  /**
   * Generate a structured commit plan from the staged diff.
   * The plan must map specific hunks/files to specific commits.
   */
  generateCommitPlan(context: RepositoryContext): Promise<CommitPlan>;

  /**
   * Generate a commit message for a single commit's hunks.
   */
  generateCommitMessage(context: CommitMessageContext): Promise<CommitMessageDraft>;

  /**
   * Generate a Pull Request title + Markdown description for the given diff.
   */
  generatePrContent(
    diff: string,
    commits: PrCommit[],
    context?: {
      branch?: string;
      baseBranch?: string;
      repoName?: string;
    }
  ): Promise<PrContent>;
}
