import { CommitPlan } from "../types/messages";

/**
 * Context about the repository passed to the AI provider.
 */
export interface RepositoryContext {
  /** The full staged diff. */
  diff: string;
  /** Current branch name, if available. */
  branch?: string;
  /** Repository name (from folder name). */
  repoName?: string;
  /** Maximum number of commits to generate. */
  maxCommits: number;
  /** Optional user instructions to bias the commit plan. */
  instructions?: string;
  /** Optional sample commit message used as a style reference. */
  sampleMessage?: string;
}

/**
 * Pull request content generated by an AI provider.
 */
export interface PrContent {
  title: string;
  description: string;
}

/**
 * AIProvider is the abstraction for generating commit plans.
 * Providers must return a valid CommitPlan, not just commit messages.
 */
export interface AIProvider {
  /**
   * Generate a structured commit plan from the staged diff.
   * The plan must map specific hunks/files to specific commits.
   */
  generateCommitPlan(context: RepositoryContext): Promise<CommitPlan>;

  /**
   * Generate a Pull Request title + Markdown description for the given diff.
   */
  generatePrContent(
    diff: string,
    commits: Array<{ subject: string; overview: string }>,
    context?: {
      branch?: string;
      baseBranch?: string;
      repoName?: string;
    }
  ): Promise<PrContent>;
}
